### ISSUE TITLE
Add new strain 'CM-237' to Aspergillus fumigatus in strain list

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/data#22]
For https://github.com/PHI-base/curation/issues/130

Discussion note copied here. @jseager7, please could you check and see if you think CM-237 is different from 237. You may already have come across this when you were doing the strain list tidy ups. Thanks.

> Strain: WT strain CM-237 is used as recipient for gene replacement and expression of mutant cyp51A allele in the study. I could locate a strain named "237" in PHI-Canto, but not CM-237. I tried searching online but I don't believe 237 and CM-237 are synonyms, so I added the strain name manually. Should we request it to be added to PHI-Canto list of A. fumigatus strains?

**Comment by jseager7** [comment]
I've checked my strain cleaning files and this strain has been '237' in PHI-base all the way back to version 4.9.

As far as I can tell, the only difference between 237 and CM-237 is provenance: 237 comes from Hope Hospital (Manchester, UK), whereas CM-237 comes from the Mycology Reference Laboratory at the Centro Nacional de Microbiologia, ISCIII (Spain).

However, since we can't guarantee that the strains are identical, I'll add CM-237 as its own entry.

**Comment by jseager7** [comment]
Note that I added the strain as 'CM237' since that had more results in a web search. I've added 'CM-237' as a synonym.
