### ISSUE TITLE
Add two wheat cultivars/strains to strain list

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/data#25]
Triticum aestivum

cv. Cadenza
cv. Courtot

For session in https://github.com/PHI-base/curation/issues/73

@jseager7, when these strains are added to the PHI-Canto strain list, will the information automatically be updated within the curation session and then eventual display in PHI5? ie will they display as 'Cadenza' or as 'cv. Cadenza'?

**Comment by jseager7** [comment]
The strain names won't be updated automatically in PHI-Canto when the strain lists are loaded, because the strain list doesn't include a mapping between old and new names (the only way this might work is by adding 'Courtot' as a synonym of 'cv. Courtot', and so on). I think I'll have to run an extra script to rename the strains in the curation sessions to their new names.

In PHI-base 5, the strains should be corrected when the JSON export is next loaded because we agreed that the data will be fully reloaded each time.

**Comment by jseager7** [comment]
Note that cv. Cadenza is already in the strain list, so I'm only adding cv. Courtot.

![image](https://github.com/PHI-base/data/assets/37659591/5e1eee22-65bf-4ad2-984b-73d8ab8ed944)
